name: Deploy Backend

on:
  push:
    branches:
      - develop 

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Set up Docker
        uses: docker/setup-buildx-action@v3

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Pull Docker Image
        run: docker pull ashleylinn/mydormstore:1.0.41

      - name: Deploy with Docker Compose
        run: |
          cd CICD
          docker compose up -d

      - name: Wait for services to be ready
        run: sleep 10

      - name: Run Health Check Test
        run: bash CICD/test-script.sh

      - name: Cleanup
        if: always()
        run: |
          cd CICD
          docker compose down
