name: Deploy Backend

on:
  push:
    branches:
      - main  # or master if you're using master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Set up Docker
        uses: docker/setup-buildx-action@v3

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Pull Docker Image
        run: docker pull ashleylinn/mydormstore:latest

      - name: Run Container
        run: docker run -d -p 5001:5001 ashleylinn/mydormstore:latest
