name: Build and Push Docker Image

on:
  push:
    branches: [main, develop]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Build and push Docker image
        run: |
          IMAGE_NAME=${{ secrets.DOCKER_USERNAME }}/mydormstore
          VERSION=1.0.${{ github.run_number }}
          docker build -t $IMAGE_NAME:latest -t $IMAGE_NAME:$VERSION -f CICD/Dockerfile .
          docker push $IMAGE_NAME:latest
          docker push $IMAGE_NAME:$VERSION
